services:
  - type: web
    name: gymapp
    runtime: java   # <--- this is required
    plan: free
    region: oregon
    branch: master  # or main if your branch is main
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/gymapp-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db.yyayftssbjgnhjcjxzjp.supabase.co:5432/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: QQQQQQWERTYUIOP@a+4714536=393
