services:
  - type: web
    name: gymapp
    env: java
    plan: free
    region: oregon
    branch: master   # make sure your branch is master, or change to main
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/gymapp-0.0.1-SNAPSHOT.jar
