services:
  - type: web
    name: gymapp
    runtime: docker
    plan: free
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d586vuili9vc739su3ug-a.oregon-postgres.render.com:5432/gymapptest
      - key: SPRING_DATASOURCE_USERNAME
        value: gymapptest
      - key: SPRING_DATASOURCE_PASSWORD
        value: wbvDRnUN74uEPjacv4A5NcfFnUXb4IYu